title: Parzon Faridani's Homepage
page-top-title: Parzon
top-section-bg-text: Data Scienctist | AI Researcher
home-subtitle: Parzon Faridani
copyright-text: '&copy; Parzon 2024-2025. All Rights Reserved.'
