title: Parzon Faridani's Homepage
page-top-title: Parzon
top-section-bg-text: AI Engineer | Applied AI Researcher
home-subtitle: Parzon Faridani
copyright-text: '&copy; Parzon 2024-2026. All Rights Reserved.'
